export const GET_PRODUCTS_LIST_PENDING = 'GET_PRODUCTS_LIST_PENDING';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAILURE = 'GET_PRODUCTS_LIST_FAILURE';

export const GET_AUTHORIZATION_PENDING = 'GET_AUTHORIZATION_PENDING';
export const GET_AUTHORIZATION_SUCCESS = 'GET_AUTHORIZATION_SUCCESS';
export const GET_AUTHORIZATION_FAILURE = 'GET_AUTHORIZATION_FAILURE';

export const GET_REGISTRATION_PENDING = 'GET_REGISTRATION_PENDING';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const SEND_ORDER_PENDING = 'SEND_ORDER_PENDING';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const GET_HISTORY_PENDING = 'GET_HISTORY_PENDING';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';
